export const CSS_STYLES = [
  {
    key: 1,
    name: "fontSize",
    id: "fontSize",
    placeholer: "e.g.:- 16px",
    label: "Font-Size: ",
  },
  {
    key: 2,
    name: "color",
    id: "color",
    placeholer: "e.g.:- red",
    label: "Font-Color: ",
  },
  {
    key: 3,
    name: "padding",
    id: "padding",
    placeholer: "e.g.:- top right bottom left",
    label: "Padding: ",
  },
  {
    key: 4,
    name: "fontFamily",
    id: "fontFamily",
    placeholer: "e.g.:- Times New Roman",
    label: "Font-Family: ",
  },
  {
    key: 5,
    name: "border",
    id: "border",
    placeholer: "e.g.:- 2px solid red",
    label: "Border: ",
  },
  {
    key: 6,
    name: "borderRadius",
    id: "borderRadius",
    placeholer: "e.g.:- 5px or 5%",
    label: "Border-Radius: ",
  },
  {
    key: 7,
    name: "boxShadow",
    id: "boxShadow",
    placeholer: "e.g.:- h v blur spread color",
    label: "Box Shadow: ",
  },
  {
    key: 8,
    name: "textShadow",
    id: "textShadow",
    placeholer: "e.g.:- h v blur spread color",
    label: "Text Shadow: ",
  },
  {
    key: 9,
    name: "textTransform",
    id: "textTransform",
    placeholer: "e.g.:- uppercase/lowecase",
    label: "Text Transform: ",
  },
  {
    key: 10,
    name: "fontWeight",
    id: "fontWeight",
    placeholer: "e.g.:- 400 <=x>= 700",
    label: "Font-Weight: ",
  },
];
